import React, {Component} from 'react'
import {ReposListReleasesResponseData} from '@octokit/types'
import {VersionViewPage} from './VersionViewPage'

interface InstallProps {
	selectedGithubRelease: ReposListReleasesResponseData | null
}

export class InstallPage extends Component<InstallProps> {
	render() {
		const selectedVersion = this.props.selectedGithubRelease || [dev]
		return (
			<div>
				{selectedVersion?.id ?? 'none'}
				install
				<VersionViewPage
					selectedGithubRelease={selectedVersion}
					onSelect={() => {}}
				/>
			</div>
		)
	}
}

const dev: ReposListReleasesResponseData = {// @ts-ignore
	'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/28099138',
	'assets_url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/28099138/assets',
	'upload_url': 'https://uploads.github.com/repos/mastercomfig/mastercomfig/releases/28099138/assets{?name,label}',
	'html_url': 'https://github.com/mastercomfig/mastercomfig/releases/tag/8.103.0',
	'id': 28099138,
	'node_id': 'MDc6UmVsZWFzZTI4MDk5MTM4',
	'tag_name': '8.103.0',
	'target_commitish': 'release',
	'name': '8.103.0',
	'draft': false,
	'author': {
		'login': 'mastercoms',
		'id': 2672245,
		'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
		'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
		'gravatar_id': '',
		'url': 'https://api.github.com/users/mastercoms',
		'html_url': 'https://github.com/mastercoms',
		'followers_url': 'https://api.github.com/users/mastercoms/followers',
		'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
		'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
		'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
		'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
		'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
		'repos_url': 'https://api.github.com/users/mastercoms/repos',
		'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
		'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
		'type': 'User',
		'site_admin': false,
	},
	'prerelease': false,
	'created_at': '2020-07-01T05:37:59Z',
	'published_at': '2020-07-01T05:42:33Z',
	'assets': [
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359911',
			'id': 22359911,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5OTEx',
			'name': 'autoexec_template.cfg',
			'label': 'autoexec template',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 55946,
			'download_count': 21,
			'created_at': '2020-07-01T05:42:44Z',
			'updated_at': '2020-07-01T05:42:44Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/autoexec_template.cfg',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359902',
			'id': 22359902,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5OTAy',
			'name': 'mastercomfig-badgpu-addon.vpk',
			'label': 'mastercomfig badgpu addon',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 455,
			'download_count': 72,
			'created_at': '2020-07-01T05:42:40Z',
			'updated_at': '2020-07-01T05:42:40Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-badgpu-addon.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359905',
			'id': 22359905,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5OTA1',
			'name': 'mastercomfig-disable-pyroland-addon.vpk',
			'label': 'mastercomfig disable pyroland addon',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 142,
			'download_count': 212,
			'created_at': '2020-07-01T05:42:42Z',
			'updated_at': '2020-07-01T05:42:42Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-disable-pyroland-addon.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359901',
			'id': 22359901,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5OTAx',
			'name': 'mastercomfig-flat-mouse-addon.vpk',
			'label': 'mastercomfig flat mouse addon',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 443,
			'download_count': 139,
			'created_at': '2020-07-01T05:42:40Z',
			'updated_at': '2020-07-01T05:42:40Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-flat-mouse-addon.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359892',
			'id': 22359892,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5ODky',
			'name': 'mastercomfig-high-preset.vpk',
			'label': 'mastercomfig high preset',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 94998,
			'download_count': 26,
			'created_at': '2020-07-01T05:42:34Z',
			'updated_at': '2020-07-01T05:42:34Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-high-preset.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359893',
			'id': 22359893,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5ODkz',
			'name': 'mastercomfig-low-preset.vpk',
			'label': 'mastercomfig low preset',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 94997,
			'download_count': 163,
			'created_at': '2020-07-01T05:42:35Z',
			'updated_at': '2020-07-01T05:42:35Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-low-preset.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359899',
			'id': 22359899,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5ODk5',
			'name': 'mastercomfig-lowmem-addon.vpk',
			'label': 'mastercomfig lowmem addon',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 525,
			'download_count': 61,
			'created_at': '2020-07-01T05:42:38Z',
			'updated_at': '2020-07-01T05:42:39Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-lowmem-addon.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359895',
			'id': 22359895,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5ODk1',
			'name': 'mastercomfig-medium-high-preset.vpk',
			'label': 'mastercomfig medium high preset',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 95005,
			'download_count': 53,
			'created_at': '2020-07-01T05:42:36Z',
			'updated_at': '2020-07-01T05:42:36Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-medium-high-preset.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359898',
			'id': 22359898,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5ODk4',
			'name': 'mastercomfig-medium-low-preset.vpk',
			'label': 'mastercomfig medium low preset',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 95004,
			'download_count': 97,
			'created_at': '2020-07-01T05:42:38Z',
			'updated_at': '2020-07-01T05:42:38Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-medium-low-preset.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359891',
			'id': 22359891,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5ODkx',
			'name': 'mastercomfig-medium-preset.vpk',
			'label': 'mastercomfig medium preset',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 95000,
			'download_count': 67,
			'created_at': '2020-07-01T05:42:33Z',
			'updated_at': '2020-07-01T05:42:34Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-medium-preset.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359907',
			'id': 22359907,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5OTA3',
			'name': 'mastercomfig-no-footsteps-addon.vpk',
			'label': 'mastercomfig no footsteps addon',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 566,
			'download_count': 43,
			'created_at': '2020-07-01T05:42:43Z',
			'updated_at': '2020-07-01T05:42:43Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-no-footsteps-addon.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359903',
			'id': 22359903,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5OTAz',
			'name': 'mastercomfig-no-soundscapes-addon.vpk',
			'label': 'mastercomfig no soundscapes addon',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 183,
			'download_count': 182,
			'created_at': '2020-07-01T05:42:41Z',
			'updated_at': '2020-07-01T05:42:41Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-no-soundscapes-addon.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359900',
			'id': 22359900,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5OTAw',
			'name': 'mastercomfig-no-tutorial-addon.vpk',
			'label': 'mastercomfig no tutorial addon',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 4940,
			'download_count': 191,
			'created_at': '2020-07-01T05:42:39Z',
			'updated_at': '2020-07-01T05:42:39Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-no-tutorial-addon.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359904',
			'id': 22359904,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5OTA0',
			'name': 'mastercomfig-null-cancelling-movement-addon.vpk',
			'label': 'mastercomfig null cancelling movement addon',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 788,
			'download_count': 119,
			'created_at': '2020-07-01T05:42:41Z',
			'updated_at': '2020-07-01T05:42:41Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-null-cancelling-movement-addon.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359906',
			'id': 22359906,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5OTA2',
			'name': 'mastercomfig-transparent-viewmodels-addon.vpk',
			'label': 'mastercomfig transparent viewmodels addon',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 596,
			'download_count': 49,
			'created_at': '2020-07-01T05:42:42Z',
			'updated_at': '2020-07-01T05:42:42Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-transparent-viewmodels-addon.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359896',
			'id': 22359896,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5ODk2',
			'name': 'mastercomfig-ultra-preset.vpk',
			'label': 'mastercomfig ultra preset',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 94999,
			'download_count': 33,
			'created_at': '2020-07-01T05:42:36Z',
			'updated_at': '2020-07-01T05:42:37Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-ultra-preset.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359897',
			'id': 22359897,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5ODk3',
			'name': 'mastercomfig-very-low-preset.vpk',
			'label': 'mastercomfig very low preset',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 95022,
			'download_count': 30,
			'created_at': '2020-07-01T05:42:37Z',
			'updated_at': '2020-07-01T05:42:37Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig-very-low-preset.vpk',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359912',
			'id': 22359912,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5OTEy',
			'name': 'mastercomfig.zip',
			'label': 'mastercomfig zip package',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 347038,
			'download_count': 13,
			'created_at': '2020-07-01T05:42:45Z',
			'updated_at': '2020-07-01T05:42:45Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/mastercomfig.zip',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359910',
			'id': 22359910,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5OTEw',
			'name': 'modules_template.cfg',
			'label': 'modules template',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 3887,
			'download_count': 30,
			'created_at': '2020-07-01T05:42:44Z',
			'updated_at': '2020-07-01T05:42:44Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/modules_template.cfg',
		},
		{
			'url': 'https://api.github.com/repos/mastercomfig/mastercomfig/releases/assets/22359909',
			'id': 22359909,
			'node_id': 'MDEyOlJlbGVhc2VBc3NldDIyMzU5OTA5',
			'name': 'template.zip',
			'label': 'user template',
			'uploader': {
				'login': 'mastercoms',
				'id': 2672245,
				'node_id': 'MDQ6VXNlcjI2NzIyNDU=',
				'avatar_url': 'https://avatars2.githubusercontent.com/u/2672245?v=4',
				'gravatar_id': '',
				'url': 'https://api.github.com/users/mastercoms',
				'html_url': 'https://github.com/mastercoms',
				'followers_url': 'https://api.github.com/users/mastercoms/followers',
				'following_url': 'https://api.github.com/users/mastercoms/following{/other_user}',
				'gists_url': 'https://api.github.com/users/mastercoms/gists{/gist_id}',
				'starred_url': 'https://api.github.com/users/mastercoms/starred{/owner}{/repo}',
				'subscriptions_url': 'https://api.github.com/users/mastercoms/subscriptions',
				'organizations_url': 'https://api.github.com/users/mastercoms/orgs',
				'repos_url': 'https://api.github.com/users/mastercoms/repos',
				'events_url': 'https://api.github.com/users/mastercoms/events{/privacy}',
				'received_events_url': 'https://api.github.com/users/mastercoms/received_events',
				'type': 'User',
				'site_admin': false,
			},
			'content_type': 'application/octet-stream',
			'state': 'uploaded',
			'size': 3000,
			'download_count': 80,
			'created_at': '2020-07-01T05:42:43Z',
			'updated_at': '2020-07-01T05:42:43Z',
			'browser_download_url': 'https://github.com/mastercomfig/mastercomfig/releases/download/8.103.0/template.zip',
		},
	],
	'tarball_url': 'https://api.github.com/repos/mastercomfig/mastercomfig/tarball/8.103.0',
	'zipball_url': 'https://api.github.com/repos/mastercomfig/mastercomfig/zipball/8.103.0',
	'body': '**Highlights:** performance optimizations and bug fixes\r\n\r\n[Support me](https://docs.mastercomfig.com/en/latest/support_me/)\r\n\r\n[**How to install**](https://docs.mastercomfig.com/en/8.103.0/setup/install/)\r\n\r\n[**How to update**](https://docs.mastercomfig.com/en/8.103.0/next_steps/update/)\r\n\r\n[Documentation](https://docs.mastercomfig.com/en/8.103.0/)\r\n\r\n***\r\n\r\n**Thanks** to the following contributor(s) for this release: micwoj92, m00n\r\n\r\n# Comfig\r\n\r\n* Added a user template, which contains all mastercomfig user files and explains how to use them\r\n  * This can solve issues where people did not know where or how to create an autoexec, class configs, or a modules file\r\n* Reduced the latency of the following actions: MOTD show, server join UI show, opening class selection menu, closing class selection menu, stopping taunts, MvM buyback, MvM loot view finish, changing class in arena when class is forced, booing as ghost, muting voice chat, re-syncing with server upon class change, starting a demo\r\n* Reduced the latency of the following commands: status, ping, pause, unpause, extendfreeze, spectate, nextmap, timeleft, ignoremsg, kill, explode\r\n* Added async partial loads being set on after first load, which improves subsequent server join times and prevents issues with animation and model mods losing their effect over time\r\n* Re-enabled out of focus sleeping to improve alt-tab performance (both during an alt-tab and improving the responsiveness of other windows)\r\n* Added periodically forcing re-sync with the server (like the record d;stop fix, but doesn\'t interfere with any demos!)\r\n* Removed redundant settings from dxsupport that are set in the config, significantly reducing config size\r\n* Increased heap memory cap (560MB, from 256MB) in dxsupport to allow for maximum data cache size (512MB, from 208MB) on supported systems\r\n* Enabled texture streaming for large and nearly always loaded textures to save memory (and removed 1 unused texture)\r\n* Enabled better sound concurrency heuristic for gun shots, for better performance and quality\r\n* Disabled additional sound precaching due to internal game precache and async sound streaming\r\n* Added a mastercomfig logo on start up\r\n* Renamed `modules.cfg` download to `modules_template.cfg`\r\n* Renamed `template.cfg` download to `autoexec_template.cfg`\r\n* Fixed `modules_template.cfg` having LF line endings, which do not work on older versions of Notepad\r\n* Fixed defaults within modules_template.cfg\r\n* Updated version output format to proper date format\r\n* Improved speed and safety of dev scripts\r\n* Moved `mat_antialias` block to an alias: `block_antialias`, which can be re-aliased by HUD authors to regain access to the command for testing\r\n\r\n# Presets\r\n\r\n* Removed `sheens_speed=off`, which turned off specialized killstreak weapon sheens, for Low, Medium Low, and Medium\r\n  * _Many users were asking how to turn this back on, so it is best if on stays as the default._\r\n\r\n# Modules\r\n\r\n## SourceTV Compatability\r\n\r\n* Added the sourcetv module, which allows the user to choose between faster spectating target changes or compatibility with SourceTV\r\n* Defaults to `sourcetv=on`, for out of the box stability.\r\n\r\n## Water\r\n\r\n* water=ultra now enforces full quality water even at long distances\r\n\r\n## Map Decals\r\n\r\n* Added periodic full decal clearing, which clears permanent decals (non [Low Priority decals](https://developer.valvesoftware.com/wiki/Infodecal)) when `decals_art=off`\r\n\r\n# Sprays\r\n\r\n* Made sprays=on only last 1 round instead of 2\r\n\r\n## Messages\r\n\r\n* Added support for latest TF2 update which disables text chat to `messages=disable`\r\n* Removed `messages=userchat` as it was not working\r\n\r\n## Voice Chat\r\n\r\n* Forced client voice state update when changing voice_chat module\r\n\r\n## Mod Support\r\n\r\n* Made mod_support=on default to prefer out of the box stability over performance\r\n\r\n# Docs\r\n\r\n* Added widescreen support to some TF2 documentation pages\r\n* Added instructions for Hardware-accelerated GPU scheduling on Windows\r\n* Switched to native dark theme\r\n* Updated launch options script for Linux to be safer\r\n* Updated cvarlist and launch options for latest TF2 update on Linux\r\n* Fixed native library information for Linux\r\n* Removed "disabling shader compilation on start" for Linux, as mastercomfig has now made this obsolete\r\n* Improved modules instructions\r\n* Added changelog mention to update instructions\r\n* Added FAQ entry for mastercomfig app\r\n* Improved syntax highlighting in many places\r\n* Switched to SVG logo from PNG to save some bytes\r\n* Added some new mods/scripts to See Also\r\n* Removed the Windows low violence mode guide, as it was removed in a recent TF2 update\r\n* Removed Felik\'s config from credits as it was deleted\r\n* Fixed possible formatting errors\r\n* Updated the localization files\r\n\r\n***\r\n\r\n[View the code changes](https://github.com/mastercomfig/mastercomfig/compare/8.102.3...8.103.0)',
}