// This file is autogenerated by tools/generate_data
// from https://github.com/mastercomfig/mastercomfig.github.io

export const autogenerated_data = {
	"autogenerated_presets_desc_en": {
		"ultra": {
			"name": "ultra",
			"desc_en": "Absolute maximum quality, with even the slightest and most performance-intensive quality improvements included."
		},
		"high": {
			"name": "high",
			"desc_en": "Enables all graphical features without making them extremely high quality."
		},
		"medium-high": {
			"name": "medium-high",
			"desc_en": "Disables unoptimized features and optimizes the game without making the game look bad."
		},
		"medium": {
			"name": "medium",
			"desc_en": "The maximum performance you can get while enabling a few effects that may give you a slight edge."
		},
		"medium-low": {
			"name": "medium-low",
			"desc_en": "The maximum performance you can get without making the game too hard to play because of awful visual quality and glitches."
		},
		"low": {
			"name": "low",
			"desc_en": "Maximum performance without caring much about visibility or possible visual glitches."
		},
		"very-low": {
			"name": "very-low",
			"desc_en": "Negatively affects playability by <strong>a lot</strong> and disables very essential features like HUD elements in desperation for performance.\n                                <br>Not recommended unless the game has such low performance that it is more of a hinderance than not having HUD elements and good player visibility.\n                                <br><strong>BY DOWNLOADING THIS PRESET YOU UNDERSTAND THAT IT <em>REMOVES HUD ELEMENTS AND REDUCES VISIBILITY</em>. IF YOU DON'T WANT THIS <em>USE LOW</em>, THAT'S THE <em>ONLY</em> DIFFERENCE.</strong>\n                            "
		}
	},
	"autogenerated_presets_en": {
		"ultra": "Ultra",
		"high": "High",
		"medium-high": "Medium High",
		"medium": "Medium",
		"medium-low": "Medium Low",
		"low": "Low",
		"very-low": "Very Low"
	},
	"autogenerated_recommended_addons": {
		"ultra": [],
		"high": [],
		"medium-high": [],
		"medium": [],
		"medium-low": [],
		"low": [
			"disable-pyroland",
			"no-soundscapes"
		],
		"very-low": [
			"no-footsteps",
			"disable-pyroland",
			"no-soundscapes",
			"no-tutorial"
		]
	},
	"autogenerated_recommended_preset": "medium-high"
}